"""Collection slug → emoji mapping for Fragment gifts."""

COLLECTION_EMOJI: dict[str, str] = {
    "artisanbrick":  "🎲",
    "astralshard":   "🔮",
    "bdaycandle":    "🎂",
    "berrybox":      "🍓",
    "bigyear":       "🔢",
    "blingbinky":    "🍼",
    "bondedring":    "💍",
    "bowtie":        "🎀",
    "bunnymuffin":   "🧁",
    "candycane":     "🍬",
    "chillflame":    "🔥",
    "cloverpin":     "🍭",
    "cookieheart":   "🍪",
    "crystalball":   "🔮",
    "cupidcharm":    "💝",
    "deskcalendar":  "📅",
    "diamondring":   "💎",
    "durovscap":     "🧢",
    "easteregg":     "🥚",
    "electricskull": "💀",
    "eternalcandle": "🕯️",
    "eternalrose":   "🌹",
    "evileye":       "🧿",
    "faithamulet":   "🧿",
    "flyingbroom":   "🧹",
    "freshsocks":    "🧦",
    "gemsignet":     "💍",
    "genielamp":     "🪔",
    "gingercookie":  "🍪",
    "hangingstar":   "⭐",
    "happybrownie":  "🍫",
    "heartlocket":   "💝",
    "heroichelmet":  "⛑️",
    "hexpot":        "🪄",
    "holidaydrink":  "🥂",
    "homemadecake":  "🎂",
    "hypnolollipop": "🍭",
    "icecream":      "🍦",
    "inputkey":      "🔑",
    "instantramen":  "🍜",
    "iongem":        "💠",
    "ionicdryer":    "💇",
    "jackinthebox":  "🎪",
    "jellybunny":    "🐰",
    "jesterhat":     "🃏",
    "jinglebells":   "🔔",
    "jollychimp":    "🐒",
    "joyfulbundle":  "🎁",
    "khabibspapakha":"🎩",
    "kissedfrog":    "🐸",
    "libertyfigure": "🗽",
    "lightsword":    "⚔️",
    "lolpop":        "🍭",
    "lootbag":       "💰",
    "lovecandle":    "🕯️",
    "lovepotion":    "🧪",
    "lowrider":      "🚗",
    "lunarsnake":    "🐍",
    "lushbouquet":   "💐",
    "madpumpkin":    "🎃",
    "magicpotion":   "🧪",
    "mightyarm":     "💪",
    "minioscar":     "🏆",
    "moneypot":      "💰",
    "moodpack":      "📦",
    "moonpendant":   "🌙",
    "moussecake":    "🎂",
    "nailbracelet":  "💅",
    "nekohelmet":    "🐱",
    "partysparkler": "🎉",
    "perfumebottle": "🧴",
    "petsnake":      "🐍",
    "plushpepe":     "🐸",
    "poolfloat":     "🏊",
    "preciouspeach": "🍑",
    "prettyposy":    "💐",
    "rarebird":      "🦜",
    "recordplayer":  "🎵",
    "restlessjar":   "🫙",
    "sakuraflower":  "🌸",
    "santahat":      "🎅",
    "scaredcat":     "🐱",
    "sharptongue":   "👅",
    "signetring":    "💍",
    "skullflower":   "💀",
    "skystilettos":  "👠",
    "sleighbell":    "🔔",
    "snakebox":      "🐍",
    "snoopcigar":    "🚬",
    "snoopdogg":     "🐶",
    "snowglobe":     "❄️",
    "snowmittens":   "🧤",
    "spicedwine":    "🍷",
    "springbasket":  "🧺",
    "spyagaric":     "🍄",
    "starnotepad":   "⭐",
    "stellarrocket": "🚀",
    "surgeboard":    "🏄",
    "swagbag":       "🛍️",
    "swisswatch":    "⌚",
    "tamagadget":    "🎮",
    "timelessbook":  "📖",
    "tophat":        "🎩",
    "toybear":       "🧸",
    "trappedheart":  "❤️",
    "ufcstrike":     "🥊",
    "valentinebox":  "💝",
    "vicecream":     "🍦",
    "victorymedal":  "🏅",
    "vintagecigar":  "🚬",
    "voodoodoll":    "🪆",
    "westsidesign":  "🤙",
    "whipcupcake":   "🧁",
    "winterwreath":  "🎄",
    "witchhat":      "🧙",
    "xmasstocking":  "🎄",
}


def get_gift_emoji(collection_slug: str, default: str = "🎁") -> str:
    """Return an emoji for the given Fragment collection slug.

    Falls back to *default* (``"🎁"``) for unknown slugs so new collections
    always get a safe placeholder until the mapping is updated.
    """
    return COLLECTION_EMOJI.get(collection_slug, default)
